---
title: "Lab 3 - Checkpoint 3"
author: "Arnaldo Gualberto"
date: "9 de maio de 2017"
output: 
  html_document:
    smart: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 0. Imports and Settings
```{r}
library(broom)
library(cluster)
library(dplyr, warn.conflicts = FALSE)
library(GGally, warn.conflicts = FALSE)
library(ggdendro)
library(ggplot2)
library(ggfortify)
library(highcharter, quietly = TRUE)
library(knitr)
library(readr)
library(tibble)
library(tidyr)
require(Rtsne, quietly = TRUE)
source('multiplot.R')
```

# 1. Análise Descritiva
```{r, message=FALSE}
dados_all <- read_csv("data/capes-cacc.csv")
glimpse(dados_all)
```

```{r}
dados <- dados_all %>%
  replace(is.na(.), 0) %>%
  mutate(periodicos_restrito = periodicos_A1 + periodicos_A2 + periodicos_B1) %>%
  mutate(periodicos_qualis = periodicos_B1 + periodicos_B2 + periodicos_B3 + periodicos_B4 + periodicos_B5) %>%
  select(instituicao = Instituição, 
         nivel = Nível, 
         colaboradores = `Docentes colaboradores`,
         permanentes = `Docentes permanentes`,
         artigos_conf = `Artigos em conf`,
         dissertacoes = Dissertacoes,
         teses = Teses,
         periodicos_restrito,
         periodicos_qualis)

dados %>% head()
```

```{r}
dados %>%
  select(-instituicao) %>%
  summary()
```

```{r}
dados %>%
  summarise(sd(colaboradores), sd(permanentes), sd(artigos_conf), sd(dissertacoes), sd(teses), sd(periodicos_qualis), sd(periodicos_restrito))
```


```{r, fig.width=12}
dados %>%
  select(-instituicao) %>%
  ggpairs()
```

```{r, fig.align="center"}
dados %>%
  ggplot(aes(x = nivel)) +
  geom_bar()
```

```{r, fig.align="center"}
dados %>%
  top_n(10, dissertacoes) %>%
  ggplot(aes(x = reorder(instituicao, dissertacoes), y = dissertacoes)) +
  geom_bar(stat = "identity") +
  coord_flip()
```

```{r, fig.align="center"}
dados %>%
  top_n(10, teses) %>%
  ggplot(aes(x = reorder(instituicao, teses), y = teses)) +
  geom_bar(stat = "identity") +
  coord_flip()
```

```{r, fig.align="center"}
dados %>%
  top_n(10, artigos_conf) %>%
  ggplot(aes(x = reorder(instituicao, artigos_conf), y = artigos_conf)) +
  geom_bar(stat = "identity") +
  coord_flip()
```

```{r, fig.align="center"}
dados %>%
  top_n(10, periodicos_qualis) %>%
  ggplot(aes(x = reorder(instituicao, periodicos_qualis), y = periodicos_qualis)) +
  geom_bar(stat = "identity") +
  coord_flip()
```

```{r, fig.align="center"}
dados %>%
  top_n(10, periodicos_restrito) %>%
  ggplot(aes(x = reorder(instituicao, periodicos_restrito), y = periodicos_restrito)) + 
  geom_bar(stat = "identity") +
  coord_flip()
```

```{r, fig.width=12}
plot_nivel <- dados %>%
  ggplot(aes(x = 0, y = nivel)) +
  geom_point(alpha = 0.3)

plot_colaboradores <- dados %>%
  ggplot(aes(x = 0, y = colaboradores)) +
  geom_point(alpha = 0.3)

plot_permanentes <- dados %>%
  ggplot(aes(x = 0, y = permanentes)) +
  geom_point(alpha = 0.3)

plot_artigos_conf <- dados %>%
  ggplot(aes(x = 0, y = artigos_conf)) +
  geom_point(alpha = 0.3)

plot_dissertacoes <- dados %>%
  ggplot(aes(x = 0, y = dissertacoes)) +
  geom_point(alpha = 0.3)

plot_teses <- dados %>%
  ggplot(aes(x = 0, y = teses)) +
  geom_point(alpha = 0.3)

plot_per_qualis <- dados %>%
  ggplot(aes(x = 0, y = periodicos_qualis)) +
  geom_point(alpha = 0.3)

plot_per_restrito <- dados %>%
  ggplot(aes(x = 0, y = periodicos_restrito)) +
  geom_point(alpha = 0.3)

multiplot(plot_nivel, plot_colaboradores, plot_permanentes, plot_artigos_conf, plot_dissertacoes, plot_teses, plot_per_qualis, plot_per_restrito, cols = 4)
```

# 2. Clusterização

```{r}
dados_pro <- dados %>%
  mutate(colaboradores = as.vector(scale(colaboradores)),
         permanentes = as.vector(scale(permanentes)),
         artigos_conf = as.vector(scale(artigos_conf+1)),
         dissertacoes = as.vector(scale(dissertacoes+1)),
         teses = as.vector(scale(teses+1)),
         periodicos_qualis = as.vector(scale(periodicos_qualis+1)),
         periodicos_restrito = as.vector(scale(periodicos_restrito+1)))

dados_pro %>% head()
```


## 2.1 Clusterização Hierárquica

```{r, fig.width=12, fig.height=10}
distancias = dados_pro %>%
  select(-instituicao) %>%
  dist(method = "maximum")

clust_hier <- distancias %>%
  hclust(method = "ward.D")

ggdendrogram(clust_hier, rotate = TRUE)
```

```{r, fig.width=12}
plot(silhouette(cutree(clust_hier, k = 4), distancias))
```


```{r, fig.width=12}
atribuicoes <- cbind(dados_pro, grupo = cutree(clust_hier, k = 4))

atribuicoes %>%
  select(-instituicao) %>%
  ggparcoord(columns = c(1:8), groupColumn="grupo", scale = "globalminmax") +
  facet_grid(paste("Grupo ", grupo) ~ .) +
  theme(legend.position = "none") +
  scale_y_continuous(breaks=c(0, 2, 4, 6))
```

## 2.2 K-Means

```{r, fig.align="center"}
set.seed(1234)
explorando_k <- tibble(k = 2:12) %>%
  group_by(k) %>%
  do(
    kmeans(select(dados_pro, -instituicao), centers = .$k, nstart = 20) %>% glance()
  )

explorando_k %>%
  ggplot(aes(x = k, y = tot.withinss)) +
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks=c(2:12))
```

```{r, fig.align="center"}
explorando_k %>%
  ggplot(aes(x = k, y = betweenss/totss)) +
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks = c(2:12))
```


```{r, fig.width=12}
km <- dados_pro %>%
  select(-instituicao) %>%
  kmeans(centers = 4, nstart = 20)

km %>%
  augment(dados_pro) %>%
  select(-instituicao) %>%
  ggparcoord(columns = c(1:8), groupColumn = ".cluster", scale = "globalminmax") +
  facet_grid(paste("Grupo ", .cluster) ~ .) +
  ylab("Z-score") +
  theme(legend.position = "none")
```

# 3. Redução da Dimensionalidade
## Principal Component Analysis (PCA)

```{r}
dados_pca <- dados_pro %>%
  select(-instituicao) %>%
  prcomp(scale = FALSE)

as.data.frame(dados_pca$rotation)
```

```{r, fig.align="center"}
tidy(dados_pca, "pcs") %>%
  ggplot(aes(x = PC, y = cumulative, label = cumulative)) +
  geom_line() +
  geom_point() +
  geom_text(vjust = 1, hjust = -.1)
```

```{r, fig.width=12}
dados_pro_aug <- km %>% augment(dados)

dados_pca %>%
  augment(dados_pro_aug) %>%
  ggplot(aes(x = .fittedPC1, y = .fittedPC2, color = .cluster)) +
  geom_point(alpha = 0.8) +
  theme(legend.position = "none")
```

```{r, fig.width=12}
p = dados_pca %>%
  augment(dados_pro_aug) %>%
  hchart("scatter", hcaes(x = .fittedPC1, y = .fittedPC2, color = .cluster)) %>%
  hc_tooltip(pointFormat = "<b>{point.instituicao}</b><br>
                     Nível: {point.nivel}<br>
             Colaboradores: {point.colaboradores}<br>
               Permanentes: {point.permanentes}<br>
             Artigos Conf.: {point.artigos_conf}<br>
              Dissertações: {point.dissertacoes}<br>
                     Teses: {point.teses}<br>
                Per. A1-B1: {point.periodicos_restrito}<br>
                Per. B2-B5: {point.periodicos_qualis}")
p
```

```{r, fig.width=12}
autoplot(dados_pca, label = F, label.size = 3, shape = T, colour = km$cluster, loadings = TRUE, loadings.color = 'red', loadings.label = TRUE, loadings.label.size = 3, loadings.label.hjust=1.1)
```

## t-SNE

```{r, fig.width=12}
set.seed(1234)
tsne.out = dados_pro %>%
  select(-instituicao) %>%
  Rtsne(perplexity = 20)

df <- as.data.frame(tsne.out$Y)
dados_tsne <- cbind(dados_pro_aug, df)

dados_tsne %>% 
  ggplot(aes(x = V1, y = V2, color = .cluster)) +
  geom_point(alpha = 0.8) +
  theme(legend.position = "none")
```


```{r}
p <- dados_tsne %>%
  hchart("scatter", hcaes(x = V1, y = V2, color = .cluster)) %>%
  hc_tooltip(pointFormat = "<b>{point.instituicao}</b><br>
                     Nível: {point.nivel}<br>
             Colaboradores: {point.colaboradores}<br>
               Permanentes: {point.permanentes}<br>
             Artigos Conf.: {point.artigos_conf}<br>
              Dissertações: {point.dissertacoes}<br>
                     Teses: {point.teses}<br>
                Per. A1-B1: {point.periodicos_restrito}<br>
                Per. B2-B5: {point.periodicos_qualis}")

p
```

