---
title: "Lab 3 - Checkpoint 2 "
author: "Anônimo"
date: "27/04/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 0. Imports and Settings
```{r}
library(cluster)
library(dplyr, warn.conflicts=FALSE)
library(GGally)
library(ggplot2)
library(knitr)
library(readr)
library(tibble)
library(tidyverse, warn.conflicts = FALSE)
source('multiplot.R')
```

Primeiramente, vou carregar os dados:

```{r, message=FALSE}
dados <- read_csv('data/movie_metadata.csv')
glimpse(dados)
```

Falar sobre valores faltando, como removi eles e os dados que selecionei (lista com marcadores).

```{r}
dados_usa = dados %>%
  filter(!duplicated(dados$movie_title)) %>%
  filter(country == 'USA' & actor_1_name == "Nicolas Cage") %>%
  filter(complete.cases(.)) %>%
  select(filme = movie_title, bilheteria = gross, orcamento = budget, duracao = duration, avaliacao = imdb_score, likes_filme = movie_facebook_likes, likes_diretor = director_facebook_likes)

head(dados_usa)
```

# 1. Análise Descritiva

```{r}
summary(dados_usa)
```

```{r}
dados_usa %>%
  filter(likes_ator == max(likes_ator))
```

```{r}
dados_usa %>%
  filter(likes_filme == max(likes_filme))
```

```{r}
dados_usa %>%
  filter(bilheteria == max(bilheteria))
```

```{r}
dados_usa %>%
  filter(orcamento == max(orcamento))
```

```{r}
dados_usa %>%
  filter(avaliacao == max(avaliacao))
```

```{r}
dados_usa %>%
  filter(duracao == max(duracao))
```


```{r, fig.width=12, fig.height=6}
dados_usa %>%
  select(-filme) %>%
  GGally::ggpairs()
```

```{r, fig.width=12}
plot_bil <- dados_usa %>%
  ggplot(aes(x = 0, y = bilheteria)) +
  geom_point(position = position_jitter(width=0.3)) +
  scale_y_log10()

plot_orc <- dados_usa %>%
  ggplot(aes(x = 0, y = orcamento)) +
  geom_point(position = position_jitter(width=0.3))

plot_dur <- dados_usa %>%
  ggplot(aes(x = 0, y = duracao)) +
  geom_point(position = position_jitter(width=0.3))

plot_ava <- dados_usa %>% 
  ggplot(aes(x = 0, y = avaliacao)) +
  geom_point(position = position_jitter(width=0.3))

plot_lf <- dados_usa %>% 
  ggplot(aes(x = 0, y = likes_filme)) +
  geom_point(position = position_jitter(width=0.3))

plot_la <- dados_usa %>% 
  ggplot(aes(x = 0, y = likes_diretor)) +
  geom_point(position = position_jitter(width=0.3))

multiplot(plot_bil, plot_orc, plot_dur, plot_ava, plot_lf, plot_la,  cols = 2)
```

# 2. Clusterização

```{r}
distancias.long <- dados_usa %>%
  select(avaliacao) %>%
  dist(method = "euclidean")

agrupamento_hs <- dados_usa %>%
  column_to_rownames("filme") %>%
  select(avaliacao) %>%
  mutate_all(funs(scale)) %>%
  dist(method = "euclidean") %>%
  hclust(method = "complete")

plot(silhouette(cutree(agrupamento_hs, k = 4), distancias.long))
```

```{r}
agrupamento_hs <- dados_usa %>%
  select(-filme) %>%
  mutate(bilheteria = scale(bilheteria), 
           orcamento = scale(orcamento),
           duracao = scale(duracao),
           likes_filme = scale(likes_filme), 
           likes_diretor = scale(likes_diretor),
           avaliacao = scale(avaliacao)) %>%
  dist(method = "euclidean") %>%
  hclust(method = "complete")

filmes = dados_usa %>%
  select(-filme) %>%
  mutate(bilheteria = scale(bilheteria), 
           orcamento = scale(orcamento),
           duracao = scale(duracao),
           likes_filme = scale(likes_filme), 
           likes_diretor = scale(likes_diretor),
           avaliacao = scale(avaliacao))

atribuicoes = tibble(k = 1:4) %>% 
    group_by(k) %>% 
    do(cbind(filmes, grupo = as.character(cutree(agrupamento_hs, .$k))))

atribuicoes_long = atribuicoes %>% 
    gather(key = "variavel", value = "valor", -k, -grupo) 

atribuicoes_long %>% 
    ggplot(aes(x = variavel, y = valor, group = grupo, colour = grupo)) + 
    geom_point(alpha = .4, position = position_dodge(width = .5)) + 
    facet_wrap(~ paste(k, " grupos")) + 
    labs(x = "", y = "z-score")
```

```{r}
filmes = dados_usa %>%
  select(-filme) %>%
  mutate(bilheteria = scale(bilheteria), 
           orcamento = scale(orcamento),
           duracao = scale(duracao),
           likes_filme = scale(likes_filme), 
           likes_diretor = scale(likes_diretor),
           avaliacao = scale(avaliacao))

agrupamento_hs <- filmes %>%
  dist(method = "euclidean") %>%
  hclust(method = "complete")

atribuicoes = tibble(k = 1:3) %>% 
    group_by(k) %>% 
    do(cbind(filmes, grupo = as.character(cutree(agrupamento_hs, .$k))))

atribuicoes %>% 
  ggparcoord(columns = c(2:7), groupColumn="grupo") +
  facet_grid(paste(k, " grupos") ~ .)

```

```{r}
data(diamonds, package="ggplot2")
diamonds.samp <- diamonds[sample(1:dim(diamonds)[1], 100), ]

# basic parallel coordinate plot, using default settings
ggparcoord(data = diamonds.samp, columns = c(1, 5:10))

# this time, color by diamond cut
ggparcoord(data = diamonds.samp, columns = c(1, 5:10), groupColumn = 2)

```

